[telegram]
# Get these values from https://my.telegram.org/apps
api_id = 33418562
api_hash = 316b85e7eef2e2f1615dee2cdee68be5
bot_token = 8626661946:AAFsSOiWciPHszYP0v2tCmTc2acCzrhAcWU

[database]
type = sqlite  # or postgresql
path = ../database/tg_manager.db  # for sqlite
# For PostgreSQL, uncomment and fill these
# host = localhost
# port = 5432
# user = username
# password = password
# database = tg_manager

[app]
debug = true
log_level = INFO
theme = dark  # or light
